### ISSUE TITLE
Add login signup in the app.

### ISSUE THREAD

**Issue by roshniRam** [NJACKWinterOfCode/Learn-Japanese#8]

**Comment by bhaskarSingh** [comment]
I would like to work on this

**Comment by ankit-kumar-dwivedi** [comment]
Is this issue open? I would like to work on this!

**Comment by bhaskarSingh** [comment]
Well, I kinda started but if you really want to work on it then go for it

On 08-Dec-2018 1:01 PM, "Ankit Kumar Dwivedi" <notifications@github.com>
wrote:

Is this issue open? I would like to work on this!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/NJACKWinterOfCode/Learn-Japanese/issues/8#issuecomment-445439228>,
or mute the thread

**Comment by ritwizsinha** [comment]
are you talking about front end or back-end validations

**Comment by bhaskarSingh** [comment]
Front end

**Comment by ritwizsinha** [comment]
i would like to work on this issue

**Comment by bhaskarSingh** [comment]
Okay

**Comment by roshniRam** [comment]
@thebishaldeb Sure go for it

**Comment by thebishaldeb** [comment]
> @thebishaldeb Sure go for it

Done! Do have a look.
